import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { ROOT } from '../repo-utils.mjs';
import { dereference, GENERATED } from './schema.mjs';

export function generatedSource(contract) {
	return `// Generated by pnpm contracts:generate. Do not edit.\nimport type { ContractSnapshot } from '../docs.js';\nexport const CONTRACT_SNAPSHOT: ContractSnapshot = ${JSON.stringify(contract, null, '\t')};\n`;
}

export function contractTables(contract, english = false) {
	const fields = (schema, omitKind = false) => {
		const object = dereference(schema, contract.$defs);
		return (
			Object.keys(object.properties)
				.filter((name) => !omitKind || name !== 'kind')
				.map((name) => `\`${name}${object.required.includes(name) ? '' : '?'}\``)
				.join(', ') || '—'
		);
	};
	return [
		`SHA-256: \`${contract.digest}\``,
		'',
		english ? '| Operation | Parameters (`?` = optional) |' : '| 操作 | 参数（`?` 表示可选） |',
		'|---|---|',
		...Object.entries(contract.operations).map(([kind, schema]) => `| \`${kind}\` | ${fields(schema, true)} |`),
		'',
		english
			? '| Backend method | MCP tool | Parameters | Read-only hint |'
			: '| Backend 方法 | MCP 工具 | 参数 | 只读提示 |',
		'|---|---|---|---|',
		...Object.entries(contract.tools).map(
			([method, tool]) =>
				`| \`${method}\` | \`${tool.name}\` | ${fields(tool.input)} | \`${tool.annotations.readOnlyHint}\` |`,
		),
		'',
		english ? '| CLI command | Installed output schema |' : '| CLI 命令 | 已安装输出 Schema |',
		'|---|---|',
		...Object.keys(contract.cli).map((command) => `| \`${command}\` | \`cli/${command}\` |`),
	].join('\n');
}

export function generatedFiles(contract, root = ROOT) {
	const files = { [GENERATED]: generatedSource(contract) };
	const backend = JSON.parse(readFileSync(path.join(root, 'packages/backend/package.json'), 'utf8'));
	assert(
		/^>=\d+$/.test(backend.engines.node),
		'Update product doctor Node range handling before changing the engine format',
	);
	const docs = {
		version: { packageName: backend.name, packageVersion: backend.version, nodeEngine: backend.engines.node },
		workflow: readFileSync(path.join(root, 'packages/backend/docs/workflow.md'), 'utf8').replaceAll('\r\n', '\n'),
		restoreLimits: readFileSync(
			path.join(root, 'docs/published-project-restore-limitations.md'),
			'utf8',
		).replaceAll('\r\n', '\n'),
		skill: readFileSync(path.join(root, 'packages/backend/docs/skills/openfairygui/SKILL.md'), 'utf8').replaceAll(
			'\r\n',
			'\n',
		),
	};
	docs.version.documentationDigest = createHash('sha256')
		.update(JSON.stringify(docs))
		.update(contract.digest)
		.digest('hex');
	files['packages/backend/src/generated/docs.ts'] =
		`// Generated by pnpm contracts:generate. Do not edit.\nexport const INSTALLED_DOCS = ${JSON.stringify(docs, null, '\t')};\n`;
	for (const [file, english] of [
		['docs/guide/contracts.md', false],
		['docs/en/guide/contracts.md', true],
	]) {
		const source = readFileSync(path.join(root, file), 'utf8').replaceAll('\r\n', '\n');
		const marker = /<!-- contracts:start -->\n[\s\S]*?\n<!-- contracts:end -->/g;
		assert.equal([...source.matchAll(marker)].length, 1, `Missing/duplicate contract section: ${file}`);
		files[file] = source.replace(
			marker,
			`<!-- contracts:start -->\n${contractTables(contract, english)}\n<!-- contracts:end -->`,
		);
	}
	for (const file of ['docs/guide/diagnostics.md', 'docs/en/guide/diagnostics.md']) {
		const source = readFileSync(path.join(root, file), 'utf8').replaceAll('\r\n', '\n');
		const marker = /<!-- diagnostics:start -->\n[\s\S]*?\n<!-- diagnostics:end -->/g;
		assert.equal([...source.matchAll(marker)].length, 1, `Missing/duplicate diagnostics section: ${file}`);
		const guides = contract.diagnostics
			.map((guide) =>
				[
					`### ${guide.code}`,
					'',
					`Owners: ${guide.owners.map((owner) => `\`${owner}\``).join(', ')} · Recovery: \`${guide.remediation.kind}\``,
					'',
					`URI: \`openfairygui://docs/diagnostics/${guide.code}\``,
					'',
					guide.remediation.message,
				].join('\n'),
			)
			.join('\n\n');
		files[file] = source.replace(marker, `<!-- diagnostics:start -->\n${guides}\n<!-- diagnostics:end -->`);
	}
	return files;
}

export function checkGeneratedFiles(files, root = ROOT) {
	for (const [file, expected] of Object.entries(files)) {
		assert(
			readFileSync(path.join(root, file), 'utf8').replaceAll('\r\n', '\n') === expected,
			`Generated contract drift: ${file}. Run pnpm contracts:generate.`,
		);
	}
}
