export {
	type UamAnimationGearBinding,
	type UamAnimationGearValue,
	type UamAssetResource,
	type UamAssetResourceKind,
	type UamButtonNode,
	type UamBlendMode,
	type UamColorGearBinding,
	type UamColorGearValue,
	type UamComboBoxNode,
	type UamComponentCustomProperty,
	type UamComponentPropertyOverride,
	type UamComponentInstanceComboItem,
	type UamComponentInstanceProperties,
	type UamComponentModel,
	type UamComponentProperties,
	type UamComponentRefNode,
	type UamComponentResource,
	type UamControllerAction,
	type UamControllerModel,
	type UamControllerPage,
	type UamDimensions,
	type UamDisplay2GearBinding,
	type UamDisplayGearBinding,
	type UamDisplayNode,
	type UamDisplayNodeBase,
	type UamDisplayNodeKind,
	type UamEdgeInsets,
	type UamFontSizeGearBinding,
	type UamFontSizeGearValue,
	type UamGearBinding,
	type UamGearPageState,
	type UamGenericAssetResource,
	type UamGraphNode,
	type UamGraphProperties,
	type UamGroupNode,
	type UamGroupProperties,
	type UamGroupableDisplayNodeBase,
	type UamIconGearBinding,
	type UamIconGearValue,
	type UamImageNode,
	type UamImageProperties,
	type UamImageResource,
	type UamImageResourceProperties,
	type UamLabelNode,
	type UamListItemData,
	type UamListNode,
	type UamListProperties,
	type UamLoader3DNode,
	type UamLoader3DProperties,
	type UamLoaderNode,
	type UamLoaderProperties,
	type UamLookGearBinding,
	type UamLookGearValue,
	type UamMovieClipNode,
	type UamMovieClipProperties,
	type UamMovieClipFrame,
	type UamMovieClipResource,
	type UamMovieClipResourceProperties,
	type UamPackage,
	type UamPackagePublish,
	type UamPackagePublishAtlas,
	type UamPackageSettings,
	type UamPoint,
	type UamProgressBarNode,
	type UamProject,
	type UamRelation,
	type UamResource,
	type UamResourceFolder,
	type UamResourceRef,
	type UamRichTextNode,
	type UamScrollBarNode,
	type UamSize,
	type UamSizeGearBinding,
	type UamSizeGearValue,
	type UamSliderNode,
	type UamPlainTextProperties,
	type UamTextGearBinding,
	type UamTextGearValue,
	type UamTextInputNode,
	type UamTextNode,
	type UamTextProperties,
	type UamTreeNode,
	type UamTreeProperties,
	type UamTransitionItem,
	type UamTransitionModel,
	type UamValidationIssue,
	type UamXYGearBinding,
	type UamXYGearValue,
	UAM_SUPPORTED_MATERIALIZATION_SCOPE,
	UAM_SUPPORTED_TRANSACTION_SCOPE,
} from './model.js';
export {
	createDefaultUamComponentProperties,
	createDefaultUamImageResourceProperties,
	createDefaultUamMovieClipResourceProperties,
	createDefaultUamPlainTextProperties,
	createDefaultUamTextProperties,
	normalizeUamProject,
} from './normalize.js';
export { assertValidUamProject, validateUamProject } from './validate.js';
export {
	commitUamProjectSourcePaths,
	liftDocumentToUamProject,
	materializeUamProject,
	readProjectAsUam,
	staleBranchDirectories,
	staleResourceFolders,
	staleSourceFiles,
	type WriteProjectFromUamOptions,
	writeProjectFromUam,
} from './bridge.js';
export {
	type AddBranchOperation,
	type AddComponentOperation,
	type AddGearOperation,
	type AddPackageOperation,
	type AddResourceOperation,
	type UpdateProjectSettingsOperation,
	type UpdatePackageSettingsOperation,
	type AddResourceFolderOperation,
	type MoveComponentOperation,
	type MoveResourceFolderOperation,
	type RemoveComponentOperation,
	type RemoveBranchOperation,
	type RemoveGearOperation,
	type RemovePackageOperation,
	type RemoveResourceOperation,
	type RemoveResourceFolderOperation,
	type RenamePackageOperation,
	type RenameBranchOperation,
	type RenameResourceFolderOperation,
	type SetComponentPropsOperation,
	type SetImageResourcePropsOperation,
	type SetResourceFavoriteOperation,
	type SetResourceFolderFavoriteOperation,
	type SetResourceExportedOperation,
	type ReplaceResourceBytesOperation,
	UamTransaction,
	UamTransactionError,
	type UamComponentSelector,
	type UamControllerSelector,
	type UamDisplayNodePropsUpdate,
	type UamDisplayNodeSelector,
	type UamGearSelector,
	type UamLookGearSelector,
	type UamPackageSelector,
	type UamResourceSelector,
	type UamResourceFolderSelector,
	type UamTransactionErrorCode,
	type UamTransactionOperation,
	type UamTransactionSupportIssueCode,
	type UamTransactionSupportIssue,
	type UamTransitionSelector,
	type UpdateGearOperation,
	applyUamTransaction,
	applyUamTransactionAsync,
	assertTransactionSupported,
	createUamTransaction,
	validateTransactionSupport,
} from './transaction.js';
