// Document
export { Document, type Transform, type TransformContext } from './document.js';

// Extension
export { Extension } from './extension.js';

// Unified Authoring Model (Gate A)
export {
	type UamAnimationGearBinding,
	type UamAnimationGearValue,
	type UamAssetResource,
	type UamAssetResourceKind,
	type UamBlendMode,
	type UamButtonNode,
	type UamColorGearBinding,
	type UamColorGearValue,
	type UamComboBoxNode,
	type UamComponentCustomProperty,
	type UamComponentPropertyOverride,
	type UamComponentInstanceComboItem,
	type UamComponentInstanceProperties,
	type UamComponentModel,
	type UamComponentProperties,
	type UamComponentRefNode,
	type UamComponentResource,
	type UamControllerAction,
	type UamControllerModel,
	type UamControllerPage,
	type UamDimensions,
	type UamDisplay2GearBinding,
	type UamDisplayGearBinding,
	type UamDisplayNode,
	type UamDisplayNodeBase,
	type UamDisplayNodeKind,
	type UamEdgeInsets,
	type UamFontSizeGearBinding,
	type UamFontSizeGearValue,
	type UamGearBinding,
	type UamGearPageState,
	type UamGenericAssetResource,
	type UamGraphNode,
	type UamGraphProperties,
	type UamGroupNode,
	type UamGroupProperties,
	type UamGroupableDisplayNodeBase,
	type UamIconGearBinding,
	type UamIconGearValue,
	type UamImageNode,
	type UamImageProperties,
	type UamImageResource,
	type UamImageResourceProperties,
	type UamLabelNode,
	type UamListItemData,
	type UamListNode,
	type UamListProperties,
	type UamLoader3DNode,
	type UamLoader3DProperties,
	type UamLoaderNode,
	type UamLoaderProperties,
	type UamLookGearBinding,
	type UamLookGearValue,
	type UamMovieClipNode,
	type UamMovieClipProperties,
	type UamMovieClipFrame,
	type UamMovieClipResource,
	type UamMovieClipResourceProperties,
	type UamPackage,
	type UamPackagePublish,
	type UamPackagePublishAtlas,
	type UamPackageSettings,
	type UamPoint,
	type UamProgressBarNode,
	type UamProject,
	type UamRelation,
	type UamResource,
	type UamResourceFolder,
	type UamResourceRef,
	type UamRichTextNode,
	type UamSize,
	type UamSizeGearBinding,
	type UamSizeGearValue,
	type UamScrollBarNode,
	type UamSliderNode,
	type UamPlainTextProperties,
	type UamTextGearBinding,
	type UamTextGearValue,
	type UamTextInputNode,
	type UamTextNode,
	type UamTextProperties,
	type UamTreeNode,
	type UamTreeProperties,
	type UamTransitionItem,
	type UamTransitionModel,
	type UamValidationIssue,
	type UamXYGearBinding,
	type UamXYGearValue,
	UAM_SUPPORTED_MATERIALIZATION_SCOPE,
	UAM_SUPPORTED_TRANSACTION_SCOPE,
	createDefaultUamComponentProperties,
	createDefaultUamImageResourceProperties,
	createDefaultUamMovieClipResourceProperties,
	createDefaultUamPlainTextProperties,
	createDefaultUamTextProperties,
	type AddBranchOperation,
	type UpdateProjectSettingsOperation,
	type UpdatePackageSettingsOperation,
	type AddComponentOperation,
	type AddPackageOperation,
	type AddResourceFolderOperation,
	type MoveComponentOperation,
	type MoveResourceFolderOperation,
	type RemoveComponentOperation,
	type RemoveBranchOperation,
	type RemovePackageOperation,
	type RemoveResourceFolderOperation,
	type RenamePackageOperation,
	type RenameBranchOperation,
	type RenameResourceFolderOperation,
	type SetComponentPropsOperation,
	type SetImageResourcePropsOperation,
	type SetResourceFavoriteOperation,
	type SetResourceFolderFavoriteOperation,
	type SetResourceExportedOperation,
	type UamComponentSelector,
	type UamControllerSelector,
	type UamDisplayNodePropsUpdate,
	type UamDisplayNodeSelector,
	type UamLookGearSelector,
	type UamResourceSelector,
	type UamResourceFolderSelector,
	type UamTransactionErrorCode,
	type UamTransactionOperation,
	type UamTransactionSupportIssueCode,
	type UamTransactionSupportIssue,
	type UamTransitionSelector,
	normalizeUamProject,
	assertValidUamProject,
	commitUamProjectSourcePaths,
	validateUamProject,
	liftDocumentToUamProject,
	materializeUamProject,
	readProjectAsUam,
	UamTransaction,
	UamTransactionError,
	applyUamTransaction,
	applyUamTransactionAsync,
	assertTransactionSupported,
	createUamTransaction,
	validateTransactionSupport,
	writeProjectFromUam,
	type WriteProjectFromUamOptions,
} from './uam/index.js';

// Authoring helpers
export {
	bindLookGear,
	composeController,
	composeTransition,
	type ControllerActionComposition,
	type ControllerCompositionOptions,
	type ControllerPageComposition,
	type LookGearBindingOptions,
	type LookGearBindingState,
	type LookGearBindingValue,
	type TransitionCompositionOptions,
	type TransitionItemComposition,
} from './authoring.js';

// Constants and Enums
export {
	VERSION,
	FGUI_MAGIC,
	NULL_STRING_INDEX,
	EMPTY_STRING_INDEX,
	PropertyType,
	PackageItemType,
	ObjectType,
	ButtonMode,
	AutoSizeType,
	AlignType,
	VertAlignType,
	LoaderFillType,
	ListLayoutType,
	ListSelectionMode,
	OverflowType,
	ProgressTitleType,
	ScrollBarDisplayType,
	ScrollType,
	FlipType,
	ChildrenRenderOrder,
	GroupLayoutType,
	PopupDirection,
	RelationType,
	FillMethod,
	FillOrigin,
	FillOrigin90,
	GraphType,
	GearType,
	TransitionActionType,
	ControllerActionType,
	EaseType,
	ObjectPropID,
	CurveType,
	ProjectType,
	type Nullable,
	type RelationDef,
} from './constants.js';

// Properties
export {
	Property,
	type IProperty,
	type PropertyResolver,
	COPY_IDENTITY,
	ExtensibleProperty,
	type IExtensibleProperty,
	ExtensionProperty,
	Root,
	Package,
	type PackageAtlasSizeOption,
	type PackageResourceFolder,
	type PackageSourceAtlas,
	type PackageSourceAtlasSettings,
	ImageResource,
	type PixelHitTestData,
	MiscResource,
	SoundResource,
	FontResource,
	MovieClipResource,
	SpineResource,
	DragonBonesResource,
	Component,
	type ComponentCustomProperty,
	Atlas,
	Sprite,
	FairyBuffer,
	FontGlyph,
	MovieFrame,
	GObject,
	type IGObject,
	GImage,
	GTextField,
	GRichTextField,
	GTextInput,
	GGraph,
	GGroup,
	GLoader,
	GLoader3D,
	GMovieClip,
	GComponent,
	GList,
	GTree,
	type GTreeItemTemplateInfo,
	type GTreeRuntimeNode,
	type GTreeInteractionState,
	type GTreeNavigationDirection,
	GButton,
	GLabel,
	GComboBox,
	GProgressBar,
	GSlider,
	GScrollBar,
	Controller,
	type ControllerHomePageType,
	ControllerPage,
	ControllerAction,
	Transition,
	TransitionItem,
	Gear,
} from './properties/index.js';

// Utilities
export {
	Logger,
	Verbosity,
	type ILogger,
	generateId,
	parseURL,
	buildURL,
	applyDerivedMovieClipModel,
	deriveMovieClipModel,
	deriveMovieClipModelFromJta,
	parseJta,
	type DerivedMovieClipFrame,
	type DerivedMovieClipModel,
	type JtaDef,
	type JtaFrame,
	type JtaTexture,
	probeRasterImage,
	type RasterImageFormat,
	type RasterImageInfo,
} from './utils/index.js';

// I/O
export {
	PlatformIO,
	ProjectReader,
	ProjectWriter,
	BinaryReader,
	BinaryWriter,
	ReaderContext,
	type BinaryWriterOptions,
	type FileSystem,
	type ProjectReadOptions,
	type ProjectBranchDirectory,
	type ProjectSourceFile,
	type ProjectWriteOptions,
} from './io/index.js';

// Types
export type {
	FairyProjectDesc,
	PublishSettings,
	CommonSettings,
	AdaptationSettings,
	JsonValue,
	CustomPropertiesSettings,
	I18nSettings,
	ProjectSettings,
} from './types/index.js';
